Dockerfile
https://docs.openshift.com/container-platform/4.17/openshift_images/create-images.html#use-uid_create-images
=> feat(dockerfile): provide the group with the same file permissions as the user.

CHANGELOG.md, backend/open_webui/apps/retrieval/vector/dbs/qdrant.py, package-lock.json, package.json
=> Fix(qdrant): Add missing query method and updated delete method for filters

CHANGELOG.md, backend/open_webui/apps/retrieval/vector/dbs/qdrant.py, package.json
=> fix(rag/qdrant): cast to int.

CHANGELOG.md, Dockerfile, package-lock.json, package.json
=> build(Dockerfile): give the same permissions as the user to the group.

CHANGELOG.md, backend/open_webui/config.py, backend/open_webui/env.py, package-lock.json, package.json
=> Fix suggestion prompts

backend/open_webui/routers/chats.py, backend/open_webui/test/apps/webui/routers/test_chats.py, src/lib/components/layout/Sidebar/ChatItem.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
=> fix: clone & clone of translations

CHANGELOG.md, package-lock.json, package.json, src/lib/components/chat/ChatPlaceholder.svelte, src/lib/components/chat/Placeholder.svelte, src/lib/components/layout/Sidebar/SearchInput.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
=> fix: Missing translations

backend/open_webui/routers/chats.py, backend/open_webui/test/apps/webui/routers/test_chats.py, src/lib/components/chat/ModelSelector/Selector.svelte, src/lib/components/layout/Sidebar/ChatItem.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
=> fix: translation issues

src/lib/components/workspace/Prompts.svelte, src/lib/components/workspace/Prompts/PromptEditor.svelte, src/lib/components/workspace/Prompts/PromptMenu.svelte
=> feat(chat-293): remove user ability to delete public prompts

src/lib/components/workspace/Prompts.svelte, src/lib/components/workspace/Prompts/PromptEditor.svelte, src/lib/components/workspace/common/AccessControl.svelte
=> feat: prevent user from creating and editing public prompt

src/lib/components/workspace/Prompts/PromptEditor.svelte
=> feat: append random suffix to command for unique prompt titles

src/lib/components/workspace/Prompts.svelte
=> fix(ui): adjust prompt item layout to extend clickable area

src/lib/components/workspace/common/AccessControl.svelte
=> feat(access control): enhance group access management with read/write toggling

src/lib/components/workspace/Prompts.svelte, src/lib/components/workspace/Prompts/PromptMenu.svelte
=> fix: remove export functionality from prompt menu

src/lib/components/chat/Navbar.svelte, src/lib/components/common/GlobalLanguageSelector.svelte, src/lib/components/layout/Help.svelte, src/lib/components/layout/Sidebar.svelte, src/lib/components/layout/TopRightControls.svelte, src/lib/i18n/locales/languages.json, src/routes/+layout.svelte, svelte.config.js
https://dsai.atlassian.net/browse/CHAT-311
https://dsai.atlassian.net/browse/CHAT-343
- **style**: Changes that …
=> feat: improve language selector UI and positioning

src/lib/components/chat/Settings/Audio.svelte
=> fix: removed unwanted audio settings

src/lib/components/chat/Settings/About.svelte
=> fix: adding required licensing

src/lib/components/layout/Help.svelte, src/lib/components/layout/Help/HelpMenu.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json, src/lib/stores.ts, src/lib/stores/index.ts
=> feat: add survey functionality to Help component and menu

src/app.html
=> fix: removed open webui content

src/app.html, src/lib/components/chat/MessageInput.svelte, src/lib/components/chat/Suggestions.svelte, src/lib/components/common/Folder.svelte, src/lib/components/common/RichTextInput.svelte, src/lib/components/layout/Sidebar.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
=> feat(accessibility): enhance ARIA attributes and improve color contrast for better accessibility

src/lib/components/admin/Settings/General.svelte
=> fix: commented-out Channel toggle in General.svelte

src/lib/components/layout/Help.svelte, src/lib/components/layout/Help/HelpMenu.svelte
=> feat: add documentation link to HelpMenu component

src/lib/components/chat/Navbar.svelte, src/lib/components/chat/Placeholder.svelte, src/lib/components/chat/Suggestions.svelte, src/lib/components/layout/TopRightControls.svelte, src/lib/stores/index.ts
…eractions
- **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing …
=> feat: added suggestion cycle prompt functionality to enhance chat interactions

src/lib/apis/chats/index.ts, src/lib/components/layout/Sidebar.svelte, src/lib/components/layout/Sidebar/SearchInput.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
=> feat: normalize tag search prefixes and improve localization support

CHANGELOG.md, package-lock.json, package.json, src/lib/components/layout/Navbar/Menu.svelte, src/lib/components/layout/Sidebar/ChatMenu.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json
* feat: remove JSON export option from Navbar and ChatMenu components
* feat: update version to 0.5.7-ccv2-1.1.1 and remove JSON export functionality from Navbar and ChatMenu components
* chore: update changelog
---------
- **perf**: …
=> fix: remove chat JSON export option

CHANGELOG.md, package-lock.json, package.json
=> feat: V0.5.7-ccv2-1.1.2

src/lib/components/layout/Sidebar/ChatItem.svelte
=> feat: improve chat title editing functionality

CHANGELOG.md, src/lib/components/layout/Sidebar/ChatMenu.svelte
=> fix: Pinned chats now see an unpinning option

CHANGELOG.md, src/lib/components/workspace/Prompts/PromptEditor.svelte, src/lib/components/workspace/Prompts/PromptViewer.svelte
=> fix: text color in dark mode & added close button

CHANGELOG.md, src/lib/components/workspace/Prompts/PromptViewer.svelte, src/routes/(app)/workspace/prompts/view/+page.svelte, src/routes/workspace/prompts/view/+page.svelte
=> fix: prompt view page visual issues

CHANGELOG.md
=> chore: fmt

src/lib/components/workspace/common/AccessControl.svelte
=> fix: undefined in reading group ids when saving

backend/requirements.txt
=> feat: add Presidio Filter dependencies to requirements

backend/open_webui/alembic.ini, backend/open_webui/migrations/README, backend/open_webui/migrations/versions/5233b3d5b959_add_domain_to_user_table.py, backend/open_webui/models/auths.py, backend/open_webui/models/users.py, backend/open_webui/routers/auths.py
=> feat: adding domain to user/auth

CHANGELOG.md, package-lock.json, package.json
=> feat: v0.5.7-ccv2-1.2.0

src/lib/components/admin/Metrics.svelte
=> feat: disabled unused Chart.js import in Metrics component

CHANGELOG.md, backend/open_webui/models/users.py, backend/open_webui/routers/auths.py, backend/open_webui/routers/users.py, src/lib/apis/users/index.ts, src/lib/components/layout/Overlay/AccountPending.svelte
=> feat: updating pending page

src/lib/apis/prompts/index.ts, src/lib/components/workspace/Prompts.svelte, src/lib/components/workspace/Prompts/PromptViewer.svelte, src/routes/(app)/workspace/prompts/edit/+page.svelte
1. **We use encodeURIComponent to URL encode the command to properly handle special characters like question marks (this was the source of the 401 on click/edit, and 405 on delete). Encoding it makes it editable and deletable again by the user.**
2. **Now that it is encoded and deletable, the user has a choice to either delete all the prompts/commands that have a question mark or any other special character or leave them alone (they will still work), but now if they go to import again either in V1 import or regular import, any special character in the command will be sanitized and replaced with a hyphen (as per command validation, we only accept alphanumeric and hyphens in the command)**
###
- **BREAKING CHANGE**: Significant …
=> fix: sanitize prompt command strings on import and ensure proper URL encoding for API requests

.github/workflows/build-release.yml, .github/workflows/docker-build.yaml, src/lib/apis/prompts/index.ts, src/lib/components/workspace/Prompts.svelte, src/lib/components/workspace/Prompts/PromptViewer.svelte, src/routes/(app)/workspace/prompts/edit/+page.svelte
=> fix: prompts commands encoding issue & ci/cd workflows

backend/requirements.txt
=> chore: update presidio dependencies to latest versions

backend/open_webui/models/message_metrics.py, backend/open_webui/models/users.py, backend/open_webui/routers/metrics.py, src/lib/apis/metrics/index.ts
=> fix: return 0 instead of None for message and user counts in metrics

src/lib/components/admin/Metrics.svelte
=> refac: metrics dashboard

src/lib/components/common/RichTextInput/AutoCompletion.js
=> fix: ensure AI suggestions start with a space when necessary

LICENSE
Align licensing terms with TBS guidance: https://www.canada.ca/en/government/system/digital-government/digital-government-innovations/open-source-software/guide-for-publishing-open-source-code.html#toc04-6:~:text=to%20remain%20anonymous.-,Appropriate%20Government%20of%20Canada%20Copyright%20Identification,-As%20per%20the
- **fix**: …
=> chore: Update LICENSE per GfPOSC

CHANGELOG.md, package-lock.json, package.json
=> chore: v0.5.7-ccv2-1.3.0 version bump

backend/requirements.txt, pyproject.toml, uv.lock
=> fix: update python-socketio to version 5.13.0 in requirements and lock files

backend/requirements.txt
=> fix(requirements): remove Presidio PII Filter dependencies

backend/open_webui/config.py, src/lib/components/admin/Settings/Interface.svelte, src/lib/components/chat/Chat.svelte, src/lib/components/common/Banner.svelte, src/lib/i18n/locales/fr-CA/translation.json, src/lib/types/index.ts
=> feat: adding localization to banners

backend/open_webui/config.py
=> refac: default suggestion prompts

backend/open_webui/config.py, backend/open_webui/retrieval/vector/dbs/qdrant.py
=> feat(retrieval/vectordb/qdrant): allow for use of disk and keeping quantization data in memory.

backend/open_webui/config.py
- **style**: Changes that do not affect the meaning of the code (white space, formatting, missing semi-colons, …
=> fix(config): update environment variable for bypassing web search embedding and retrieval

backend/open_webui/routers/metrics.py, backend/open_webui/routers/models.py, src/lib/components/workspace/Metrics.svelte, src/lib/i18n/locales/en-GB/translation.json, src/lib/i18n/locales/fr-CA/translation.json, src/routes/(app)/workspace/+layout.svelte, src/routes/(app)/workspace/metrics/+page.svelte
- Updated metrics API to allow analysts to see all models, while filtering metrics data by domain.
- Adjusted model retrieval logic to grant access to all models for admin, analyst, and global_analyst roles.
- Improved Metrics component to load and display all available models for analysts, with domain filtering applied in API calls.
- Added loading state for metrics display to enhance user experience.
- Updated translations for loading metrics message in English and French.
- Implemented user data loading checks in layout and metrics page to ensure proper navigation and access control.
- **build**: Changes that affect the build system or external …
=> fix(metrics): Enhance model metrics access and display for analysts

backend/open_webui/retrieval/web/brave.py
Quick fix to ensure brave results are conform to standards.
=> fix(retrieval/web/brave): excise any results whose URLs do not conform to standard.

pyproject.toml
=> feat(mcp): add new dependencies for fastmcp, pytz, crewai, and azure-storage-blob to toml file

backend/requirements.txt, pyproject.toml
=> fix(mcp): update dependencies for pydantic, google-generativeai, crewai, and crewai-tools in requirements and pyproject files

backend/crew_mcp_integration.py, backend/open_webui/main.py, backend/open_webui/socket/main.py, backend/open_webui/socket/utils.py
=> fix(socket): improve error handling in Redis lock management and cleanup task

src/lib/components/workspace/common/AccessControl.svelte
Adding Code Suggestion for https://dsai.atlassian.net/browse/CHAT-820
- **style**: Changes that do not affect …
=> refac: access control component based on roles and groups availability

backend/open_webui/main.py
=> fix(healthcheck): improve database health check with timeout and error handling

CHANGELOG.md, backend/open_webui/models/feedbacks.py, backend/open_webui/models/prompts.py, backend/open_webui/routers/evaluations.py, backend/open_webui/routers/prompts.py, src/lib/apis/evaluations/index.ts, src/lib/apis/prompts/index.ts, src/lib/components/admin/Evaluations.svelte, src/lib/components/admin/Evaluations/Feedbacks.svelte, src/lib/components/workspace/Prompts.svelte, src/routes/(app)/+layout.svelte
| Metric | Old System | New System | Improvement |
|--------|------------|------------|-------------|
| Initial Load Time | 19ms | 8ms | **58% faster** |
| Memory Usage | 520KB | 20KB | **96% less** |
| Network Transfer | 520KB | 20KB | **96% less** |
| DOM Elements | 522 | 20 | **96% less** |
| Search Speed | Client-side filtering | Database indexes | **10x faster** |
| Scalability | Degrades with data | Constant performance | **∞ better** |
| Mobile Experience | Slow, data-heavy | Fast, data-light | **Dramatically better** |
Old System: Performance degrades as data grows
- 100 prompts or feedbacks → OK
- 1,000 prompts or feedbacks → Slow
- 10,000 prompts or feedbacks → Unusable
New System: Consistent performance regardless of data size
- 100 prompts or feedbacks → 8ms
- 1,000 prompts or …
=> feat(prompts): add pagination to prompt list for improved navigation

backend/open_webui/retrieval/utils.py, backend/open_webui/routers/retrieval.py
This was definitely an error when initially implemented: https://github.com/open-webui/open-webui/commit/57010901e6077dbb12417f90dd99bbdd83b30d42#diff-2b402262bca06b34bb1c5088d0443e37b9ee1ce7a7f0099b6e3c41a9d5f9e38cR380
=> fix(retrieval/full-context): change to correct config.

CHANGELOG.md, package-lock.json, package.json
Changes: https://github.com/ssc-dsai/canchat-v2/compare/v0.5.7-ccv2-1.5.0...ssc-dsai:canchat-v2:e3ab377bb40c8c789b734e5919381e9dc3b4482a
=> release(0.5.7-ccv2-1.6.0): update versions and changelog.

backend/open_webui/models/prompts.py, backend/open_webui/routers/prompts.py
=> fix(prompts): issue where public prompts were not being seen by user

backend/open_webui/models/prompts.py, backend/open_webui/routers/prompts.py
This fixes a performance issue noticed in dev and uat after the previous fix.
=> feat(prompts): optimize prompt retrieval with access control and public prompts

backend/open_webui/models/prompts.py, backend/open_webui/routers/prompts.py, src/lib/components/workspace/Prompts.svelte
admins can view/create/edit/delete all public and private prompts
non-admin can view/create/edit/delete only their own private prompts but can only view public prompts
=> fix(prompts): update access control logic for public and private prompts

backend/open_webui/models/prompts.py, backend/open_webui/routers/prompts.py
fixed prompt query logic for sqlite and posgresql
=> fix(prompts): fixed prompt query logic for sqlite and posgresql

CHANGELOG.md, backend/open_webui/routers/retrieval.py, package-lock.json, package.json
=> fix(retrieval): add missing dependency. chat-879

.github/workflows/docker-build.yaml, Dockerfile
Last attempt to cleanup the runner. If this doesn't work, we will pivot to a private runner with more space.
=> feat(docker): enhance cleanup processes in Docker build to optimize disk usage

Dockerfile
=> fix(docker): update permissions handling to skip multiple large static asset directories for improved space management

.github/workflows/docker-build.yaml, Dockerfile
=> refactor(docker): revert previous attempts of solving runner build space issue

.github/workflows/docker-build.yaml
=> fix(docker-build): disable cache-to option to avoid disk space issues

Dockerfile
=> fix(dockerfile): set HF_HOME environment variable for txtai model loading

Dockerfile, backend/open_webui/config.py, backend/open_webui/grounding/wiki_search_utils.py
=> fix(Dockerfile): update cache destination and environment variables for Hugging Face models

src/lib/components/admin/Users/UserList/EditUserModal.svelte
When using the Edit User window from the Users tab in the Admin panel, changing a user's role and hitting save did not work. The role change was ignored and not persisted in the database, making it impossible for administrators to modify user permissions through the Edit User modal.
Enhanced the `EditUserModal.svelte` component to properly handle role updates by utilizing the existing role-specific API endpoint alongside the general user update endpoint.
- **Enhanced `EditUserModal.svelte`**: Fixed role update functionality by implementing proper API calls
1. **Separates API concerns** - Uses appropriate endpoints for different update types
2. **Detects role changes** - Compares original role with modified role before making API calls
3. **Dual API approach**:
- Updates basic user info …
=> feat(user): add role update functionality in EditUserModal

src/lib/components/chat/Chat.svelte
=> fix(chat): clear sessionStorage for default models on new chats

backend/open_webui/grounding/context_analysis.py, backend/open_webui/grounding/wiki_search_utils.py
=> feat(grounding): enhance query processing with temporal context and improve logging

src/lib/components/chat/Controls/Controls.svelte
=> fix(controls): set Advanced Params collapsible to closed by default

backend/open_webui/grounding/wiki_search_utils.py
=> feat(wiki-search): implement query-specific locks to prevent concurrent processing of identical queries
